apiVersion: ptp.openshift.io/v1
kind: PtpCfg
metadata:
  name: example-ptpcfg
spec:
  profile:
  - name: "profile1"
    interface: "eth0"
    ptp4lOpts: "-s -2"
    phc2sysOpts: "-a -r"
  recommend:
  - profile: "profile1"
    priority: 4
    match:
    - nodeLabel: "node-role.kubernetes.io/worker="
      nodeName: "nfvpe-13.oot.lab.eng.bos.redhat.com"
