apiVersion: apps/v1
kind: Deployment
metadata:
  name: ptp-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: ptp-operator
  template:
    metadata:
      labels:
        name: ptp-operator
    spec:
      serviceAccountName: ptp-operator
      containers:
        - name: ptp-operator
          # Replace this with the built image name
          image: quay.io/zenghui/ptp-operator:v0.0.1
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "ptp-operator --alsologtostderr -v 10" ]
          imagePullPolicy: Never
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "ptp-operator"
            - name: LINUXPTP_DAEMON_IMAGE
              value: "zenghui/ptp-daemon:latest"
